### ISSUE TITLE
Backend should store and make available the factorizations of sequence entries

### ISSUE THREAD

**Issue by gwhitney** [numberscope/backscope#12]
The desire to easily look at sequence entries in terms of their prime factorizations is one of the primary motivations/justifications for having a Numberscope backend distinct from the OEIS. This information can be computed just once, and stored for easy access and manipulation in the frontscope, rather than burdening viewers' browsers with performing the factorizations on the client side.

**Comment by katestange** [comment]
Some more specific suggestions.

(1) For a URL, we could use: `http://[SERVER]/api/get_oeis_factored/[OEIS ID]/[NUM]`

(2) In the vast majority of cases where you want the sequence factored for some purpose, you would want to treat -1 differently.  But it would be convenient to be able to loop through a list of factors otherwise.  So how about an object (dictionary) like
```
type Factorization = {
  sign: BigInt; // either 1 or -1
  factors: BigInt[][]; // list of two-element lists [p,e] indicating factor p**e, where p is prime, e is exponent, in increasing order of p
};
```
Then, someone who wants to iterate through the prime powers can do so easily, and the sign is also easy to call.

**Comment by gwhitney** [comment]
Kate also raised two related questions:
1. How to fail gracefully when an entry is too big to factor?
2. How to deal with the fact that factorization could be slow and browser might have to wait?

**Comment by gwhitney** [comment]
On 1 I think the answer should be as close to the same as possible for dealing with missing entries of base sequences, but we haven't settled on that yet.

**Comment by gwhitney** [comment]
On 2, I think that factorization should happen in the background on any base sequence that's been requested, and in the interval until that happens, the unfactored entries show up as missing just as if (1) were the case.
