### ISSUE TITLE
psycopg-2 install fails during setup

### ISSUE THREAD

**Issue by katestange** [numberscope/backscope#23]
Suggestion is that we replace psycopg2 with psycopg2-binary in requirements.txt.  If this seems like a good idea, it's probably a nice easy PR for me to do.

Here's the backstory:
For both myself and Steven, trying to set up the backend, we ran into this issue when running `pip install -r requirements.txt`.
```
Collecting psycopg2==2.9.1
  Downloading psycopg2-2.9.1.tar.gz (379 kB)
     |████████████████████████████████| 379 kB 37.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/katestange/data/projects/numberscope/frontscope-backscope/backscope/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q_gkpnj5/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q_gkpnj5/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-q_gkpnj5/psycopg2/pip-egg-info
         cwd: /tmp/pip-install-q_gkpnj5/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-install-q_gkpnj5/psycopg2/pip-egg-info/psycopg2.egg-info
    writing /tmp/pip-install-q_gkpnj5/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-q_gkpnj5/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-q_gkpnj5/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-q_gkpnj5/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Manually installing psycopg-2 resulted in the same error, but the following worked:
`pip install psycopg2-binary`
Then, we had to delete the corresponding line from requirements.txt and rerun.

**Comment by samzhang111** [comment]
This looks like a good move to me.

Double-checking the [psycopg2 installation instructions](https://www.psycopg.org/docs/install.html#quick-install) I see that:

1. psycopg2-binary is the recommended way to quickly install psycopg2
2. In my opinion, there's a lot of value in prioritizing ease of installation at this stage of the application. Besides, the risks of using psycopg2-binary described in the documentation ([psycopg vs. psycopg-binary](https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary)) are minimal for the type of application we're developing

**Comment by gwhitney** [comment]
For some counterpoint, as Kate points out in #24, the readme currently assumes you know how to install postgres and have done so. I didn't hit the difficulty highlighted in this issue because typically pg_config comes along with doing the postgres installation, and it did for me. So in fact, if we resolve #24 in such a way that the readme steps a person installing through postgres installation, and does it before the `pip install` step of concern here, then this issue will likely become a non-issue altogether. Hence, I am in favor of resolving #24 first and then revisiting this one. Of course if someone is motivated to do this immediately and submits a PR, it should be acted on as usual.

**Comment by samzhang111** [comment]
Maybe #24 solves this, but I'm not sure! There could still be specific C libraries required by psycopg that aren't packaged by postgres. In addition, we may want to make it easier for the user to install backscope without postgres for a variety of reasons, for example they could postgres inside a virtual machine or Docker or whatever, and this would allow that to happen more easily.

Also it seems to me preferable for the project to be robust to the order in which you install these things (postgres vs. backscope), even if we do prescribe a particular order in the instructions, especially since there's no logical reason why you'd expect to need to install postgres before backscope's Python dependencies can be installed.

Mostly this is out of a suspicion that even after changing the instructions, there will still remain incidents where we have to remind a new project member, "oh, right, you need psycopg2-binary instead of psycopg2."

**Comment by gwhitney** [comment]
Well, as I said, I totally respect the approach decided on by whomever puts in the time for a PR for #23 and/or #24. Was just trying to provide the perspective that I never encountered this issue, along with what seems like a reasonable explanation for the difference in my case.
