### ISSUE TITLE
Can we upgrade Debian?

### ISSUE THREAD

**Issue by liam-mulhall** [numberscope/backscope#39]
This is an issue for the server itself and not backscope, so technically it doesn't belong in this repo. (I suppose we could make another repo if we have a lot of issues like this.) I digress.

I've been trying (unsuccessfully) to get backscope installed on the server. I'm running into issues because the installed version of Python (3.5) is old (see the deprecation warning below). I can't upgrade Python because (I think) 3.5 is the newest version of Python in Debian 9.13's package repo.

```
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
```

Even if I weren't running into these issues with Python or if I mucked around and installed a new version of Python without using `apt`, Debian is dropping LTS for Debian Stretch on June 30:

![lts](https://user-images.githubusercontent.com/60749003/170143682-68955c2f-0812-47b0-9554-69ffec8dc525.png)

See https://wiki.debian.org/LTS for more info.

It would be nice if we could upgrade to the newest version of Debain so that we can get all of the latest and greatest stuff. If we decide to go forward with an upgrade, I suppose we'll have to figure out what, if anything, needs to be saved from the server and then we'll need to contact Jeff Taylor.

@katestange and @gwhitney, what are your thoughts?

**Comment by gwhitney** [comment]
If the server is a machine we totally control, I see absolutely no reason we shouldn't completely wipe it and put whatever convenient operating system on it we want. Python 3.5 is absolutely out-of-date and there is no reason we should be using it. I personally don't care what distro/version of linux is on the server -- it should just be easy to upgrade/administer/etc.

If we don't directly administer the server, then we should just ask the admin to upgrade it to whatever current Linux distro is easy for the admin.

AFAIK, there is nothing on the server that needs to be retained. In general, we should keep things so that it is totally safe to just start with a fresh server at any time. Any information that might be on the server for proper operation of the backscope should be checked into the repository first, of course.

So as far as I am concerned, fire away with upgrading.

And I agree, this is a conversation much better had on Slack (channel backend, I presume) as it is transitory and unrelated to the codebase. So closing in favor of completing the discussion (if there is even any more discussion to be had) on Slack.
